### PR TITLE
Setting Parameters For Distributions After Initialization

### PR DESCRIPTION
**Pull request by giftonian**
I suggest to add setters function for MEAN and VARIANCE. Reason behind this is a need to work with different distribution object in a loop. If we don't have these setters function, then we have to create an object of Normal class in each iteration of loop passing its Mean and Variance in the constructor. Instead, we can create only one object outside the loop and keep setting MEAN and VARIANCE in each iteration for every different distribution.

### CODE REVIEW

**Comment by gburtini** [comment]
Thanks @giftonian -- I agree this is a good idea. Each distribution has different parametrizations and we should support this everywhere. Could you update the other distributions accordingly before we merge this?

**Comment by giftonian** [comment]
OK @gburtini ,  I am going to add this for other distributions as well

**Comment by giftonian** [comment]
@gburtini 
You can merge it now.

**Comment by gburtini** [comment]
Thanks @giftonian, looks good. I'll do a quick cleanup and merge this ASAP.

**Pull request merged**
